--- #Demo from Linux Academy Ansible 407 course
- hosts:  la
  become:  yes
  tasks:  
    - name:  Install apache
      yum: 
        name:  httpd
        state:  latest
    - name:  Start and enable httpd
      service:  
        name:  httpd
        state:  started
        enabled:  yes
    - name:  Create index.html
      file:  
        path: /var/www/html/index.html
        state: touch
    - name:  Add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello world!\nAnsible is great!"




 
