--- #Testing the register action

- hosts:  la 
  tasks:
    - name:  Create file
      file:
        path:  /tmp/newfile
        state:  touch
      register:  output
    - debug:  msg="Register output is {{output}}"
    - name:  edit file
      lineinfile:
        path:  /tmp/newfile
        line:  "{{output.uid}}"



